package picker

// unicodeEmoji is a curated table of common unicode emoji with shortcode-style
// names and search keywords. It is intentionally a hand-picked subset covering
// the most frequently used emoji across the standard groups (smileys, gestures,
// people, animals, food, activities, travel, objects, symbols) rather than the
// full Unicode CLDR set, which keeps the binary small while still making the
// picker useful. Entries are ordered roughly by group; FilterEmoji preserves
// this order within each match tier.
var unicodeEmoji = []Emoji{
	// Smileys & emotion
	{"😀", "grinning", []string{"smile", "happy", "face"}},
	{"😃", "smiley", []string{"happy", "joy", "face"}},
	{"😄", "smile", []string{"happy", "laugh", "face"}},
	{"😁", "grin", []string{"happy", "smile"}},
	{"😆", "laughing", []string{"lol", "haha", "satisfied"}},
	{"😅", "sweat_smile", []string{"relief", "nervous"}},
	{"🤣", "rofl", []string{"lol", "rolling", "laugh"}},
	{"😂", "joy", []string{"lol", "tears", "laugh", "cry"}},
	{"🙂", "slight_smile", []string{"smile"}},
	{"🙃", "upside_down", []string{"silly", "sarcasm"}},
	{"😉", "wink", []string{"flirt", "eye"}},
	{"😊", "blush", []string{"happy", "smile", "shy"}},
	{"😇", "innocent", []string{"angel", "halo"}},
	{"🥰", "smiling_face_with_three_hearts", []string{"love", "adore"}},
	{"😍", "heart_eyes", []string{"love", "crush"}},
	{"🤩", "star_struck", []string{"wow", "eyes", "stars"}},
	{"😘", "kissing_heart", []string{"kiss", "love"}},
	{"😗", "kissing", []string{"kiss"}},
	{"😋", "yum", []string{"tongue", "delicious", "tasty"}},
	{"😛", "stuck_out_tongue", []string{"tongue", "playful"}},
	{"😜", "stuck_out_tongue_winking_eye", []string{"tongue", "wink", "silly"}},
	{"🤪", "zany", []string{"goofy", "crazy", "wild"}},
	{"🤔", "thinking", []string{"hmm", "consider", "think"}},
	{"🤨", "raised_eyebrow", []string{"skeptical", "suspicious"}},
	{"😐", "neutral", []string{"meh", "blank"}},
	{"😑", "expressionless", []string{"blank", "meh"}},
	{"😶", "no_mouth", []string{"silence", "quiet"}},
	{"🙄", "roll_eyes", []string{"annoyed", "whatever"}},
	{"😏", "smirk", []string{"smug", "sly"}},
	{"😬", "grimacing", []string{"awkward", "yikes"}},
	{"😴", "sleeping", []string{"zzz", "tired", "sleep"}},
	{"😌", "relieved", []string{"calm", "content"}},
	{"😔", "pensive", []string{"sad", "down"}},
	{"😢", "cry", []string{"sad", "tear"}},
	{"😭", "sob", []string{"cry", "bawl", "sad"}},
	{"😤", "triumph", []string{"steam", "proud", "angry"}},
	{"😠", "angry", []string{"mad", "annoyed"}},
	{"😡", "rage", []string{"mad", "furious", "angry"}},
	{"🤬", "cursing", []string{"swear", "angry", "symbols"}},
	{"😱", "scream", []string{"shock", "fear", "omg"}},
	{"😨", "fearful", []string{"scared", "afraid"}},
	{"😰", "cold_sweat", []string{"nervous", "anxious"}},
	{"😥", "disappointed_relieved", []string{"phew", "sad"}},
	{"😓", "sweat", []string{"exhausted", "hot"}},
	{"🤗", "hugging", []string{"hug", "embrace"}},
	{"🤭", "hand_over_mouth", []string{"giggle", "oops"}},
	{"🤫", "shushing", []string{"quiet", "secret", "shh"}},
	{"🤥", "lying", []string{"pinocchio", "liar"}},
	{"😳", "flushed", []string{"embarrassed", "shy", "blush"}},
	{"🥵", "hot_face", []string{"heat", "sweating"}},
	{"🥶", "cold_face", []string{"freezing", "frozen"}},
	{"😵", "dizzy_face", []string{"knocked", "woozy"}},
	{"🤯", "exploding_head", []string{"mind", "blown", "shock"}},
	{"😷", "mask", []string{"sick", "medical", "covid"}},
	{"🤒", "thermometer_face", []string{"sick", "ill", "fever"}},
	{"🤕", "head_bandage", []string{"hurt", "injured"}},
	{"🤢", "nauseated", []string{"sick", "gross", "vomit"}},
	{"🤮", "vomiting", []string{"puke", "sick", "gross"}},
	{"🥳", "partying", []string{"party", "celebrate", "hat"}},
	{"😎", "sunglasses", []string{"cool", "shades"}},
	{"🤓", "nerd", []string{"geek", "glasses"}},
	{"🧐", "monocle", []string{"inspect", "fancy"}},
	{"😕", "confused", []string{"unsure"}},
	{"😟", "worried", []string{"anxious"}},
	{"🙁", "slight_frown", []string{"sad"}},
	{"☹️", "frowning", []string{"sad"}},
	{"😮", "open_mouth", []string{"wow", "surprise"}},
	{"😲", "astonished", []string{"shock", "amazed"}},
	{"🥺", "pleading", []string{"puppy", "eyes", "beg"}},
	{"😖", "confounded", []string{"frustrated"}},
	{"😣", "persevere", []string{"struggle"}},
	{"😞", "disappointed", []string{"sad", "let down"}},
	{"😩", "weary", []string{"tired", "ugh"}},
	{"😫", "tired_face", []string{"exhausted", "ugh"}},
	{"🥱", "yawning", []string{"bored", "sleepy"}},
	{"😤", "huff", []string{"frustrated"}},
	{"💀", "skull", []string{"dead", "dying", "lol"}},
	{"👻", "ghost", []string{"boo", "spooky", "halloween"}},
	{"👽", "alien", []string{"ufo", "space"}},
	{"🤖", "robot", []string{"bot", "ai"}},
	{"💩", "poop", []string{"crap", "turd"}},
	{"🤡", "clown", []string{"joker"}},
	{"😈", "smiling_imp", []string{"devil", "evil"}},
	{"👿", "imp", []string{"devil", "angry"}},

	// Hearts & symbols
	{"❤️", "heart", []string{"love", "red"}},
	{"🧡", "orange_heart", []string{"love"}},
	{"💛", "yellow_heart", []string{"love"}},
	{"💚", "green_heart", []string{"love"}},
	{"💙", "blue_heart", []string{"love"}},
	{"💜", "purple_heart", []string{"love"}},
	{"🖤", "black_heart", []string{"love", "dark"}},
	{"🤍", "white_heart", []string{"love"}},
	{"💔", "broken_heart", []string{"heartbreak", "sad"}},
	{"❣️", "heart_exclamation", []string{"love"}},
	{"💕", "two_hearts", []string{"love"}},
	{"💞", "revolving_hearts", []string{"love"}},
	{"💓", "heartbeat", []string{"love", "pulse"}},
	{"💗", "heartpulse", []string{"love", "growing"}},
	{"💖", "sparkling_heart", []string{"love"}},
	{"💘", "cupid", []string{"love", "arrow"}},
	{"💝", "gift_heart", []string{"love", "present"}},
	{"💯", "hundred", []string{"100", "perfect", "score"}},
	{"💢", "anger", []string{"mad", "symbol"}},
	{"💥", "boom", []string{"explosion", "collision"}},
	{"💫", "dizzy", []string{"stars", "sparkle"}},
	{"💦", "sweat_drops", []string{"water", "splash"}},
	{"💨", "dash", []string{"wind", "fast"}},
	{"🔥", "fire", []string{"lit", "flame", "hot"}},
	{"✨", "sparkles", []string{"shiny", "stars", "glitter"}},
	{"⭐", "star", []string{"favorite"}},
	{"🌟", "star2", []string{"glowing", "shining"}},
	{"⚡", "zap", []string{"lightning", "electric"}},
	{"☀️", "sunny", []string{"sun", "weather"}},
	{"🌙", "crescent_moon", []string{"night", "moon"}},
	{"⛄", "snowman", []string{"winter", "snow"}},
	{"☃️", "snowman_snow", []string{"winter", "snow"}},
	{"🌈", "rainbow", []string{"pride", "colorful"}},
	{"✅", "white_check_mark", []string{"check", "yes", "done", "green"}},
	{"☑️", "ballot_check", []string{"check", "tick"}},
	{"✔️", "heavy_check_mark", []string{"check", "yes", "done"}},
	{"❌", "x", []string{"cross", "no", "wrong"}},
	{"❎", "negative_squared_cross", []string{"no", "cross"}},
	{"❓", "question", []string{"help", "what"}},
	{"❗", "exclamation", []string{"warning", "important"}},
	{"⚠️", "warning", []string{"caution", "alert"}},
	{"🚫", "no_entry_sign", []string{"forbidden", "ban", "stop"}},
	{"💤", "zzz", []string{"sleep", "tired"}},

	// Hand gestures
	{"👍", "thumbsup", []string{"like", "yes", "approve", "+1"}},
	{"👎", "thumbsdown", []string{"dislike", "no", "-1"}},
	{"👌", "ok_hand", []string{"okay", "perfect"}},
	{"🤌", "pinched_fingers", []string{"italian", "chef"}},
	{"✌️", "v", []string{"peace", "victory"}},
	{"🤞", "crossed_fingers", []string{"luck", "hope"}},
	{"🤟", "love_you_gesture", []string{"ily"}},
	{"🤘", "metal", []string{"rock", "horns"}},
	{"🤙", "call_me_hand", []string{"shaka", "hang loose"}},
	{"👈", "point_left", []string{"finger"}},
	{"👉", "point_right", []string{"finger"}},
	{"👆", "point_up_2", []string{"finger"}},
	{"👇", "point_down", []string{"finger"}},
	{"☝️", "point_up", []string{"finger", "one"}},
	{"✋", "raised_hand", []string{"stop", "high five"}},
	{"🤚", "raised_back_of_hand", []string{"stop"}},
	{"🖐️", "hand_splayed", []string{"five", "stop"}},
	{"🖖", "vulcan", []string{"spock", "star trek"}},
	{"👋", "wave", []string{"hello", "hi", "bye"}},
	{"🤝", "handshake", []string{"deal", "agree"}},
	{"👏", "clap", []string{"applause", "bravo"}},
	{"🙌", "raised_hands", []string{"praise", "hooray"}},
	{"🙏", "pray", []string{"thanks", "please", "hope"}},
	{"✊", "fist", []string{"power", "solidarity"}},
	{"👊", "punch", []string{"fist", "bump"}},
	{"🤛", "left_facing_fist", []string{"bump"}},
	{"🤜", "right_facing_fist", []string{"bump"}},
	{"💪", "muscle", []string{"strong", "flex", "gym"}},
	{"🫶", "heart_hands", []string{"love"}},
	{"🫡", "saluting", []string{"salute", "respect", "yes sir"}},
	{"🖕", "middle_finger", []string{"rude", "flip off"}},
	{"✍️", "writing_hand", []string{"write", "sign"}},

	// People & activities
	{"👀", "eyes", []string{"look", "watching", "see"}},
	{"👁️", "eye", []string{"look", "see"}},
	{"🧠", "brain", []string{"smart", "mind"}},
	{"🦴", "bone", []string{"skeleton"}},
	{"👶", "baby", []string{"infant"}},
	{"🧒", "child", []string{"kid"}},
	{"👦", "boy", []string{"kid"}},
	{"👧", "girl", []string{"kid"}},
	{"🧑", "adult", []string{"person"}},
	{"👨", "man", []string{"male"}},
	{"👩", "woman", []string{"female"}},
	{"🧓", "older_adult", []string{"elder"}},
	{"🕺", "man_dancing", []string{"dance", "disco"}},
	{"💃", "dancer", []string{"dance", "salsa"}},
	{"🏃", "runner", []string{"run", "exercise"}},
	{"🚶", "walking", []string{"walk", "pedestrian"}},
	{"🧘", "person_in_lotus", []string{"yoga", "meditate"}},
	{"🎉", "tada", []string{"party", "celebrate", "congrats"}},
	{"🎊", "confetti_ball", []string{"party", "celebrate"}},
	{"🎈", "balloon", []string{"party", "birthday"}},
	{"🎁", "gift", []string{"present", "birthday"}},
	{"🎂", "birthday", []string{"cake", "party"}},
	{"🏆", "trophy", []string{"win", "award", "champion"}},
	{"🥇", "first_place", []string{"gold", "medal", "win"}},
	{"🥈", "second_place", []string{"silver", "medal"}},
	{"🥉", "third_place", []string{"bronze", "medal"}},
	{"⚽", "soccer", []string{"football", "ball"}},
	{"🏀", "basketball", []string{"ball", "hoops"}},
	{"🏈", "football", []string{"nfl", "ball"}},
	{"⚾", "baseball", []string{"ball"}},
	{"🎮", "video_game", []string{"gaming", "controller"}},
	{"🎲", "game_die", []string{"dice", "random"}},
	{"🎯", "dart", []string{"target", "bullseye"}},
	{"🎵", "musical_note", []string{"music", "song"}},
	{"🎶", "notes", []string{"music", "song"}},
	{"🎤", "microphone", []string{"sing", "karaoke"}},
	{"🎧", "headphones", []string{"music", "listen"}},

	// Animals & nature
	{"🐶", "dog", []string{"puppy", "pet"}},
	{"🐱", "cat", []string{"kitten", "pet"}},
	{"🐭", "mouse", []string{"rodent"}},
	{"🐹", "hamster", []string{"pet"}},
	{"🐰", "rabbit", []string{"bunny"}},
	{"🦊", "fox", []string{"animal"}},
	{"🐻", "bear", []string{"animal"}},
	{"🐼", "panda", []string{"bear"}},
	{"🐨", "koala", []string{"animal"}},
	{"🐯", "tiger", []string{"animal"}},
	{"🦁", "lion", []string{"animal", "king"}},
	{"🐮", "cow", []string{"animal", "moo"}},
	{"🐷", "pig", []string{"animal", "oink"}},
	{"🐸", "frog", []string{"animal", "toad"}},
	{"🐵", "monkey_face", []string{"animal"}},
	{"🐔", "chicken", []string{"animal", "hen"}},
	{"🐧", "penguin", []string{"animal"}},
	{"🐦", "bird", []string{"animal"}},
	{"🦄", "unicorn", []string{"magic", "horse"}},
	{"🐝", "bee", []string{"honey", "insect"}},
	{"🦋", "butterfly", []string{"insect"}},
	{"🐢", "turtle", []string{"animal", "slow"}},
	{"🐍", "snake", []string{"animal"}},
	{"🐙", "octopus", []string{"animal", "sea"}},
	{"🦑", "squid", []string{"animal", "sea"}},
	{"🐳", "whale", []string{"animal", "sea"}},
	{"🐬", "dolphin", []string{"animal", "sea"}},
	{"🐠", "tropical_fish", []string{"animal", "sea"}},
	{"🌸", "cherry_blossom", []string{"flower", "spring"}},
	{"🌹", "rose", []string{"flower", "love"}},
	{"🌻", "sunflower", []string{"flower"}},
	{"🌷", "tulip", []string{"flower"}},
	{"🌲", "evergreen_tree", []string{"tree", "forest"}},
	{"🌴", "palm_tree", []string{"tree", "beach"}},
	{"🍀", "four_leaf_clover", []string{"luck", "irish"}},
	{"🍁", "maple_leaf", []string{"autumn", "fall"}},

	// Food & drink
	{"🍏", "green_apple", []string{"fruit"}},
	{"🍎", "apple", []string{"fruit", "red"}},
	{"🍌", "banana", []string{"fruit"}},
	{"🍉", "watermelon", []string{"fruit"}},
	{"🍇", "grapes", []string{"fruit"}},
	{"🍓", "strawberry", []string{"fruit"}},
	{"🍒", "cherries", []string{"fruit"}},
	{"🍑", "peach", []string{"fruit", "butt"}},
	{"🍆", "eggplant", []string{"aubergine", "veggie"}},
	{"🌶️", "hot_pepper", []string{"spicy", "chili"}},
	{"🌽", "corn", []string{"veggie"}},
	{"🍕", "pizza", []string{"food", "slice"}},
	{"🍔", "hamburger", []string{"burger", "food"}},
	{"🍟", "fries", []string{"food", "chips"}},
	{"🌭", "hotdog", []string{"food"}},
	{"🌮", "taco", []string{"food", "mexican"}},
	{"🌯", "burrito", []string{"food", "mexican"}},
	{"🍜", "ramen", []string{"noodles", "food"}},
	{"🍣", "sushi", []string{"food", "japanese"}},
	{"🍦", "icecream", []string{"dessert", "soft serve"}},
	{"🍩", "doughnut", []string{"donut", "dessert"}},
	{"🍪", "cookie", []string{"dessert"}},
	{"🍫", "chocolate_bar", []string{"dessert", "candy"}},
	{"🍿", "popcorn", []string{"movie", "snack"}},
	{"☕", "coffee", []string{"drink", "cafe", "tea"}},
	{"🍵", "tea", []string{"drink", "matcha"}},
	{"🍺", "beer", []string{"drink", "pint"}},
	{"🍻", "beers", []string{"cheers", "drink"}},
	{"🍷", "wine_glass", []string{"drink"}},
	{"🍸", "cocktail", []string{"drink", "martini"}},
	{"🥂", "champagne_glasses", []string{"cheers", "toast"}},

	// Travel & objects
	{"🚗", "car", []string{"vehicle", "auto"}},
	{"🚕", "taxi", []string{"cab", "vehicle"}},
	{"🚌", "bus", []string{"vehicle"}},
	{"🚑", "ambulance", []string{"emergency"}},
	{"🚓", "police_car", []string{"cop", "emergency"}},
	{"🚲", "bike", []string{"bicycle", "cycle"}},
	{"✈️", "airplane", []string{"flight", "travel"}},
	{"🚀", "rocket", []string{"space", "launch", "ship"}},
	{"🛸", "ufo", []string{"alien", "space"}},
	{"⛵", "sailboat", []string{"boat", "sea"}},
	{"🚢", "ship", []string{"boat", "cruise"}},
	{"🏠", "house", []string{"home", "building"}},
	{"🏢", "office", []string{"building", "work"}},
	{"💻", "computer", []string{"laptop", "pc"}},
	{"🖥️", "desktop", []string{"computer", "pc"}},
	{"📱", "iphone", []string{"phone", "mobile"}},
	{"⌨️", "keyboard", []string{"typing"}},
	{"🖱️", "mouse_three_button", []string{"click"}},
	{"💾", "floppy_disk", []string{"save", "disk"}},
	{"💡", "bulb", []string{"idea", "light"}},
	{"🔦", "flashlight", []string{"torch", "light"}},
	{"🔋", "battery", []string{"power", "charge"}},
	{"🔌", "electric_plug", []string{"power", "charge"}},
	{"📷", "camera", []string{"photo", "picture"}},
	{"🎥", "movie_camera", []string{"film", "record"}},
	{"📺", "tv", []string{"television"}},
	{"🔔", "bell", []string{"notification", "ring"}},
	{"🔕", "no_bell", []string{"mute", "silent"}},
	{"📢", "loudspeaker", []string{"announce", "loud"}},
	{"🔒", "lock", []string{"secure", "closed"}},
	{"🔓", "unlock", []string{"open"}},
	{"🔑", "key", []string{"unlock", "password"}},
	{"🔨", "hammer", []string{"tool", "build"}},
	{"🔧", "wrench", []string{"tool", "fix"}},
	{"⚙️", "gear", []string{"settings", "cog"}},
	{"🧲", "magnet", []string{"attract"}},
	{"💰", "moneybag", []string{"cash", "rich"}},
	{"💵", "dollar", []string{"money", "cash"}},
	{"💳", "credit_card", []string{"money", "pay"}},
	{"📈", "chart_up", []string{"stocks", "growth", "trend"}},
	{"📉", "chart_down", []string{"stocks", "loss", "trend"}},
	{"📅", "calendar", []string{"date", "schedule"}},
	{"📌", "pushpin", []string{"pin", "location"}},
	{"📎", "paperclip", []string{"attach"}},
	{"✏️", "pencil2", []string{"write", "edit"}},
	{"📝", "memo", []string{"note", "write", "pencil"}},
	{"📖", "book", []string{"read", "open"}},
	{"🔍", "mag", []string{"search", "zoom", "find"}},
	{"🔎", "mag_right", []string{"search", "zoom"}},
	{"💊", "pill", []string{"medicine", "drug"}},
	{"🩹", "adhesive_bandage", []string{"bandaid", "hurt"}},
	{"🎓", "mortar_board", []string{"graduate", "school"}},
}
