package app

import (
	"strconv"
	"sync/atomic"
	"time"
)

const discordEpochMilliseconds = int64(1420070400000)

var interactionNonceSequence atomic.Uint32

// newInteractionNonce returns a decimal Discord-style snowflake. Unlike a
// message nonce, interaction nonces are generated by the Discord client as
// snowflakes and should not reuse the UUID-based optimistic-message nonce.
func newInteractionNonce() string {
	milliseconds := time.Now().UnixMilli() - discordEpochMilliseconds
	sequence := uint64(interactionNonceSequence.Add(1) & ((1 << 22) - 1))
	return strconv.FormatUint(uint64(milliseconds)<<22|sequence, 10)
}
